### ISSUE TITLE
Choose a less ambiguous name?

### ISSUE THREAD

**Issue by bradleyjkemp** [bradleyjkemp/memviz#17]
It's been pointed out that memmap already has a conflicting meaning.
Creating this ticket to guage reaction and vote on suggestions.
Should the name be changed? Suggestions welcome.

**Comment by bradleyjkemp** [comment]
Visualization is a better analogy than mapping so: memvis?

(structvis also suggested but "struct" is again ambiguous)

**Comment by wader** [comment]
memviz if you want to play on the z in graphviz

**Comment by bradleyjkemp** [comment]
Ok, plan of action for the rename:

1. Rename Github repo
2. Run tests and merge #23. This includes an import comment which will prevent users from cloning the repo under the old name (which wouldn't work because the import paths would be wrong)
3. Hope this doesn't break too many people 🙏

**Comment by wader** [comment]
🎉
