### ISSUE TITLE
Update Reame : How to use this ?

### ISSUE THREAD

**Issue by jatin69** [bradleyjkemp/memviz#33]
### Expected Behaviour
Update readme for reflect - How to use this app? where to install? which languages are supported? If i am not a go user, and still want it, how can that be made possible? A code snipped would do wonders.

### Actual Behaviour
The code usage behavior. Actual installation or how to include it is not mentioned?

**Comment by salmanulfarzy** [comment]
Minimal example is available at https://godoc.org/github.com/bradleyjkemp/memviz

**Comment by jatin69** [comment]
Oh, is it possible to have this for other languages? Python maybe?

**Comment by salmanulfarzy** [comment]
Quick google search gives this https://github.com/parrt/lolviz

**Comment by jatin69** [comment]
Thanks 😄
