### ISSUE TITLE
Please tag new release -- post rename

### ISSUE THREAD

**Issue by tep** [bradleyjkemp/memviz#39]
_I'm forgoing your issue template since it's format is orthogonal to the issue at hand._

The latest tagged release (`v0.2.2`) is from 25 Jan 2018 -- back when the package was still named `memmap`.  This is what gets downloaded by `go get` when using a modern (i.e. module-aware) version of Go.

Therefore, if I import `"github.com/bradleyjkemp/memviz"` into a project that uses modules, I'm compelled to reference it as package `memmap`... and this acutely unballances my already precarious feng shui.

Please tag a new release where the package name and the repo's basename agree.

Thankyouverymuchandhaveaniceday.

**Comment by bradleyjkemp** [comment]
Wow yeah that's a big oversight 🤦‍♂Just tagged the current master as v0.2.3 which should fix the issue. Thanks for raising this! 🙂
