### ISSUE TITLE
How to see visual graph?

### ISSUE THREAD

**Issue by 68696c6c** [bradleyjkemp/memviz#47]
The readme shows a graphic of a data structure.  Does memviz support vizualizing a data structure?  If so, are there any examples of how to do this?

**Comment by bradleyjkemp** [comment]
Hi @68696c6c, yes the example in the README was generated by this test case: https://github.com/bradleyjkemp/memviz/blob/1d8faf13bbfcc3a19622f9234b1837512a28f523/memviz_test.go#L175

It outputs a map of the datastructure in the "dot" format like this: https://github.com/bradleyjkemp/memviz/blob/1d8faf13bbfcc3a19622f9234b1837512a28f523/.snapshots/TestFib#L1

You can then feed that through https://graphviz.org/ (or try http://webgraphviz.com/) to turn that text representation into an actual image.

**Comment by 68696c6c** [comment]
Ok, thank you I was missing the graphviz part!  Would you mind if I sent you a PR to update the readme with that?

**Comment by bradleyjkemp** [comment]
Sure thing! It's buried in the Usage section at the moment (https://github.com/bradleyjkemp/memviz#user-content-usage:~:text=pipe%20the%20output%20into%20graphviz) so absolutely appreciate improvements to make it more obvious :)

**Comment by 68696c6c** [comment]
Ok.  I've updated the readme in a branch but I don't have access to push it up to make a PR.  I can fork the repo or just paste the code here, whichever you prefer.

**Comment by bradleyjkemp** [comment]
Whichever you prefer 🙂 Fork and open PR if you want the GitHub contribution stats or just paste here and I'm happy to make the change

**Comment by 68696c6c** [comment]
Ok, I've forked the repo and created a PR here: https://github.com/bradleyjkemp/memviz/pull/48
